auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  log_format: json

memberlist:
  join_members: []

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
  compaction_interval: 10m

limits_config:
  # Ingestion limits
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_streams_per_user: 20000
  max_line_size: 512000
  
  # Query limits
  max_query_series: 500
  max_query_parallelism: 32
  max_query_length: 721h
  max_concurrent_tail_requests: 10
  
  # Retention
  retention_period: 720h
  
  # Rate limiting
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 20MB
  
  # Label limits
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30

frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true

frontend_worker:
  parallelism: 10

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 512
        ttl: 1h
  cache_results: true
  max_retries: 5
  split_queries_by_interval: 15m

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

analytics:
  reporting_enabled: false
